name: Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Event Name
        run: echo " ${{ github.event_name }}  ${{ github.event.ref_type }}  ${{ github.ref }} "

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      # - name: Install Dependencies
      #   run: cd BonAppetit && npm ci --force

      # - name: Build Angular App
      #   run: cd BonAppetit && npm run build
    
      - name: Deploy to EC2 Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "BonAppetit/dist/bon-appetit/*"
          target: "/home/ubuntu/Nehal/freshBuild"
  
      - name: Move bon-appetit folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mv /home/ubuntu/Nehal/freshBuild/BonAppetit/dist/bon-appetit /home/ubuntu/Nehal/freshBuild/
          
      - name: Remove BonAppetit folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf /home/ubuntu/Nehal/freshBuild/BonAppetit

      - name: Clear Backup folder if not empty
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(ls -A /home/ubuntu/Nehal/backupBuild)" ]; then
              sudo rm -rf /home/ubuntu/Nehal/backupBuild/*
            fi
      - name: SSH into EC2 Instance and execute commands to backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(ls -A /home/ubuntu/Nehal/currentBuild)" ]; then
              sudo cp -r /home/ubuntu/Nehal/currentBuild/* /home/ubuntu/Nehal/backupBuild
            fi
      - name: Clear Current folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ "$(ls -A /home/ubuntu/Nehal/currentBuild)" ]; then
              sudo rm -rf /home/ubuntu/Nehal/currentBuild/*
            fi
      - name: SSH into EC2 Instance and execute commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/ubuntu/Nehal/freshBuild/bon-appetit/* /home/ubuntu/Nehal/currentBuild
