name: Deploy Angular App

on:
  push:
    branches:
      - master
    tags:
      - 'release-demo-*'

jobs:
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release-demo-')
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Event Name
        run: echo " ${{ github.event_name }}  ${{ github.event.ref_type }}  ${{ github.ref }} "

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: cd BonAppetit && npm ci --force

      - name: Build Angular App
        run: cd BonAppetit && npm run build

      - name: Clear OMS folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/Nehal/freshBuild/*

      - name: Deploy to EC2 Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: BonAppetit/dist/bon-appetit/* # Or the directory where your Angular app is built
          target: /home/ubuntu/Nehal/freshBuild
          
      - name: Clear Backup folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/Nehal/backupBuild/*
  
      - name: SSH into EC2 Instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo cp -r /home/ubuntu/Nehal/currentBuild/* /home/ubuntu/Nehal/backupBuild

      - name: Clear Current folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/Nehal/currentBuild/*

      - name: SSH into EC2 Instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo cp -r /home/ubuntu/Nehal/freshBuild/* /home/ubuntu/Nehal/currentBuild
