name: copying folder to ec2 instance
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME  }}
        key: ${{ secrets.EC2_SSH_KEY  }}
        port: ${{ secrets.PORT }}
        source: BonAppetit
        target: /home/ubuntu/code

