name: Deploy Angular App

on:
  push:
    branches:
      - master
    tags:
      - 'release-demo-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: ls && cd BonAppetit && npm i --force

      - name: Build Angular App
        run: cd BonAppetit && npm run build

      - name: Deploy to EC2 Instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: BonAppetit/dist/ # Or the directory where your Angular app is built
          target: /home/ubuntu/code

      - name: SSH into EC2 Instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/code/bon-appetit
            ls 
            sudo cp -r /home/ubuntu/code/test_delete
            sudo cp -r /home/ubuntu/code/BonAppetit/dist/bon-appetit/* /home/ubuntu/test_backup
            
